### ISSUE TITLE
Image Sizes

### ISSUE THREAD

**Issue by andrewmbacon** [common-place-dot-org/commonplace#11]
Figure out a way to keep all the images the same size/orientation. 

* Only grab certain size? Like thumbnail.
* Grab the "medium" size, but then use JS to crop it with overflow hidden?

**Comment by sammenza** [comment]
I found you can use this 

if ( has_post_thumbnail() ) {
		the_post_thumbnail(array(150,150)); //Replace 150 to whatever size you want
	}
