### ISSUE TITLE
Article Filters

### ISSUE THREAD

**Issue by andrewmbacon** [common-place-dot-org/commonplace#9]
Add ability to filter articles page by Issue, and by Column. 

Check this out to get started: https://wordpress.org/support/topic/show-categories-filter-on-custom-post-type-list

It didn't work, but it might have enough clues to figure it out the rest of the way.

**Comment by sammenza** [comment]
Yup that's the next thing I'm going to be working on.

**Comment by sammenza** [comment]
Found the solution, you can now filter by Issue, however you can't filter by Issue and Column at the same time...that still needs work
